language: python

python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.8-dev"
    - "nightly"
    - "pypy3"

env:
    - DJANGO_VERSION=2.2
    - DJANGO_VERSION=3.0

jobs:
    exclude:
        - python: "3.5"
          env: DJANGO_VERSION=3.0
    allow_failures:
        - python: "3.8-dev"
        - python: "nightly"

install:
    - pip install -q pipenv
    - pipenv install
    - pipenv install Django==$DJANGO_VERSION

script:
    - pipenv run pip freeze
    - pipenv run python manage.py test npb
